#!/usr/bin/env node

/**
 * Code generation script for vitest-chrome-mv3
 * Reads vitest-chrome-schema.json and generates src/generated.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Generates code for a namespace recursively
 */
function generateNamespace(namespaceName, schema, indent = 2, parentPath = '') {
  const spaces = ' '.repeat(indent);
  const lines = [];
  lines.push(`${spaces}${namespaceName}: {`);

  // Build full namespace path (e.g., "system.display" or just "alarms")
  const fullNamespacePath = parentPath
    ? `${parentPath}.${namespaceName}`
    : namespaceName;

  // Generate functions
  for (const fn of schema.functions || []) {
    const fullName = `chrome.${fullNamespacePath}.${fn.name}`;
    const options = fn.isPromise ? `{ isPromise: true }` : '';
    lines.push(
      `${spaces}  ${fn.name}: genericFunction('${fullName}'${options ? `, ${options}` : ''}),`,
    );
  }

  // Generate events
  for (const event of schema.events || []) {
    lines.push(`${spaces}  ${event.name}: createEvent(),`);
  }

  // Generate properties (as undefined for now, can be overridden)
  for (const prop of schema.properties || []) {
    lines.push(`${spaces}  ${prop.name}: undefined,`);
  }

  // Generate nested namespaces
  for (const key in schema) {
    if (
      key !== 'functions' &&
      key !== 'events' &&
      key !== 'properties' &&
      typeof schema[key] === 'object' &&
      schema[key] !== null &&
      !Array.isArray(schema[key])
    ) {
      const nestedSchema = schema[key];
      const nestedCode = generateNamespace(
        key,
        nestedSchema,
        indent + 2,
        fullNamespacePath,
      );
      lines.push(nestedCode);
    }
  }

  lines.push(`${spaces}},`);
  return lines.join('\n');
}

/**
 * Main generation function
 */
function generateMock() {
  const schemaPath = join(__dirname, '../src/vitest-chrome-schema.json');
  const outputPath = join(__dirname, '../src/generated.ts');

  console.log('Reading schema from:', schemaPath);
  const schemaContent = readFileSync(schemaPath, 'utf-8');
  const schema = JSON.parse(schemaContent);

  const lines = [];
  lines.push('// AUTO-GENERATED - DO NOT EDIT');
  lines.push('// This file is generated by scripts/generate-mock.js');
  lines.push('// To regenerate, run: npm run build:mock');
  lines.push('');
  lines.push("import { genericFunction, createEvent } from './utils';");
  lines.push('');
  lines.push('export const generatedChrome = {');

  // Generate each top-level namespace
  for (const namespaceName in schema) {
    const namespaceSchema = schema[namespaceName];
    const namespaceCode = generateNamespace(namespaceName, namespaceSchema, 2);
    lines.push(namespaceCode);
  }

  lines.push('};');
  lines.push('');

  const output = lines.join('\n');
  writeFileSync(outputPath, output, 'utf-8');
  console.log('Generated:', outputPath);
  console.log('✓ Code generation complete');
}

generateMock();

